version: '3'
services:
  app:
    image: 20240410-backend
    init: true
    volumes:
      - ./data:/workspace/data
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    env_file:
      - .env
    environment:
      - PORT
